name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World Step
        run: echo "Hello, World!"

      - name: Print the GitHub User
        run: echo "The user who triggered this workflow is ${{ github.actor }}"

      - name: Create a Loop
        run: |
          for i in {1..5}; do
            echo i$
          done

      - name: Simulate Build Process
        run: |
          echo "Building..."
          sleep 2
          echo "Done!"

  info:
    runs-on: ubuntu-latest
    steps:
      - name: Print System Information
        run: uname -a

      - name: Print CPU Information
        run: lscpu